### ISSUE TITLE
No version provided for dependency org.junit.jupiter:junit-jupiter-api

### ISSUE THREAD

**Issue by mpatnode** [openrewrite/rewrite-maven-plugin#308] opened 2022-03-03 00:27 UTC
So this only happens on one of my projects, and  I hard coded in the dependency for my project as well as the plug in itself, but no luck.     Note, the plugin was also complaining about missing kotlin.jvm.JvmInline, which I did manage to fix.

[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.20.0:run (default-cli) on project pab-security: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.20.0:run failed: No version provided for dependency org.junit.jupiter:junit-jupiter-api -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.20.0:run (default-cli) on project pab-security: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.20.0:run failed: No version provided for dependency org.junit.jupiter:junit-jupiter-api
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.20.0:run failed: No version provided for dependency org.junit.jupiter:junit-jupiter-api
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.openrewrite.maven.internal.MavenParsingException: No version provided for dependency org.junit.jupiter:junit-jupiter-api
    at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies (ResolvedPom.java:476)
    at org.openrewrite.maven.tree.ResolvedPom.resolveDependencies (ResolvedPom.java:452)
    at org.openrewrite.maven.tree.MavenResolutionResult.resolveDependencies (MavenResolutionResult.java:138)
    at org.openrewrite.maven.UpdateMavenModel.updateResult (UpdateMavenModel.java:130)
    at org.openrewrite.maven.UpdateMavenModel.lambda$visitDocument$3 (UpdateMavenModel.java:100)
    at org.openrewrite.marker.Markers.lambda$computeByType$0 (Markers.java:97)
    at org.openrewrite.internal.ListUtils.lambda$map$0 (ListUtils.java:149)
    at org.openrewrite.internal.ListUtils.map (ListUtils.java:131)
    at org.openrewrite.internal.ListUtils.map (ListUtils.java:149)
    at org.openrewrite.marker.Markers.computeByType (Markers.java:92)
    at org.openrewrite.maven.UpdateMavenModel.visitDocument (UpdateMavenModel.java:39)
    at org.openrewrite.xml.tree.Xml$Document.acceptXml (Xml.java:114)
    at org.openrewrite.xml.tree.Xml.accept (Xml.java:51)
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:199)
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:218)
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:218)
    at org.openrewrite.TreeVisitor.visitNonNull (TreeVisitor.java:159)
    at org.openrewrite.maven.AddDependency$1.visitDocument (AddDependency.java:200)
    at org.openrewrite.maven.AddDependency$1.visitDocument (AddDependency.java:175)
    at org.openrewrite.xml.tree.Xml$Document.acceptXml (Xml.java:114)
    at org.openrewrite.xml.tree.Xml.accept (Xml.java:51)
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:199)
    at org.openrewrite.maven.AddDependency.lambda$visit$3 (AddDependency.java:202)
    at java.util.Optional.map (Optional.java:260)
    at org.openrewrite.maven.AddDependency.lambda$visit$4 (AddDependency.java:175)
    at org.openrewrite.internal.ListUtils.lambda$map$0 (ListUtils.java:149)
    at org.openrewrite.internal.ListUtils.map (ListUtils.java:131)
    at org.openrewrite.internal.ListUtils.map (ListUtils.java:149)
    at org.openrewrite.maven.AddDependency.visit (AddDependency.java:174)
    at org.openrewrite.RecipeScheduler.scheduleVisit (RecipeScheduler.java:244)
    at org.openrewrite.RecipeScheduler.scheduleVisit (RecipeScheduler.java:287)
    at org.openrewrite.RecipeScheduler.scheduleVisit (RecipeScheduler.java:287)
    at org.openrewrite.RecipeScheduler.scheduleVisit (RecipeScheduler.java:287)
    at org.openrewrite.RecipeScheduler.scheduleVisit (RecipeScheduler.java:287)
    at org.openrewrite.RecipeScheduler.scheduleVisit (RecipeScheduler.java:287)
    at org.openrewrite.RecipeScheduler.scheduleVisit (RecipeScheduler.java:287)
    at org.openrewrite.RecipeScheduler.scheduleRun (RecipeScheduler.java:79)
    at org.openrewrite.Recipe.run (Recipe.java:247)
    at org.openrewrite.Recipe.run (Recipe.java:238)
    at org.openrewrite.Recipe.run (Recipe.java:234)
    at org.openrewrite.maven.AbstractRewriteMojo.listResults (AbstractRewriteMojo.java:179)
    at org.openrewrite.maven.RewriteRunMojo.execute (RewriteRunMojo.java:41)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR]

pom.xml:
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.britive.pab.security</groupId>
    <artifactId>pab-security</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>pab-commons-security</name>
    <description>Helper library for PAB Spring Boot JPA Security Apps</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.9.RELEASE</version>
        <relativePath /> 
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>
        <start-class>com.britive.pab.Application</start-class>
    </properties>

    <dependencies>

        <dependency>
            <groupId>com.britive.pab.api</groupId>
            <artifactId>pab-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.12.0</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-cognitoidp</artifactId>
            <version>1.12.151</version>
        </dependency>

        <dependency>
            <groupId>com.github.jgonian</groupId>
            <artifactId>commons-ip-math</artifactId>
            <version>1.32</version>
        </dependency>

        <dependency>
            <groupId>com.vaadin.external.google</groupId>
            <artifactId>android-json</artifactId>
            <version>0.0.20131108.vaadin1</version>
        </dependency>

        
        <dependency>
            <groupId>org.bitbucket.b_c</groupId>
            <artifactId>jose4j</artifactId>
            <version>0.6.5</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-sns</artifactId>
            <version>1.12.151</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
            <version>1.12.151</version>
        </dependency>

        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
        </dependency>

        <dependency>
            <groupId>com.vladmihalcea</groupId>
            <artifactId>hibernate-types-5</artifactId>
            <version>2.3.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.integration</groupId>
            <artifactId>spring-integration-file</artifactId>
            <version>4.2.3.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>com.blueconic</groupId>
            <artifactId>browscap-java</artifactId>
            <version>1.2.8</version>
        </dependency>

        
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.12.151</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-core</artifactId>
            <version>1.12.151</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-kinesis</artifactId>
            <version>1.12.151</version>
        </dependency>
        
        <dependency>
			<groupId>com.britive</groupId>
			<artifactId>secret-manager-utils</artifactId>
			<version>1</version>
		</dependency>

		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
		</dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.8.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>4.20.0</version>
                <configuration>
                    <activeRecipes>
                        <recipe>org.openrewrite.java.spring.boot2.SpringBoot1To2Migration</recipe>
                    </activeRecipes>
                    <pomCacheEnabled>false</pomCacheEnabled>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.jupiter</groupId>
                        <artifactId>junit-jupiter-api</artifactId>
                        <version>5.8.2</version>
                    </dependency>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-stdlib</artifactId>
                        <version>1.5.10</version>
                    </dependency>
                    <dependency>
                        <groupId>org.openrewrite.recipe</groupId>
                        <artifactId>rewrite-spring</artifactId>
                        <version>4.16.0</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>`

**Comment by mpatnode** [comment] 2022-03-03 00:48
OK.  Now pretty sure this belongs in the core rewrite project and may be a dup.   Looks like the system generated a pom file which it then didn't like when it parsed it.  Turning on -DskipMavenParsing=true allowed it to complete.

**Comment by tkvangorder** [comment] 2022-03-03 23:55
@mpatnode Thank you for reporting this issue, I believe this is a duplicate of https://github.com/openrewrite/rewrite/issues/1422

I am going to close this issue and please feel free to track the progress of 1422.

**Closed by tkvangorder** 2022-03-03 23:55 UTC
