### ISSUE TITLE
Recipe parameter validation broken in 5.39.2

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-maven-plugin#849] opened 2024-08-29 11:15 UTC
## What is the smallest, simplest way to reproduce the problem?
Upgrade from 5.39.1 with this recipe enabled
```
org.openrewrite.staticanalysis.RemoveUnusedLocalVariables
```

## What did you see instead?

```
Recipe validation error in RemoveUnusedLocalVariables.ignoreVariablesNamed: is required
```
That validation message is wrong, the parameter is not required: https://docs.openrewrite.org/recipes/staticanalysis/removeunusedlocalvariables
This could be related to the Nullable annotation change from Openrewrite to JSpecify. The validation of recipe parameters is also based on whether fields are nullable or not, and maybe that doesn't fully work with the new annotation classes anymore.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Probably not.

**Comment by timtebeek** [comment] 2024-08-29 11:21
Thanks! This is a duplicate of
- https://github.com/openrewrite/rewrite-static-analysis/issues/333

**Closed by timtebeek** 2024-08-29 11:21 UTC
Labels: bug, duplicate
