### ISSUE TITLE
Error when i want to exec rewrite:remove since version 4.34.0

### ISSUE THREAD

**Issue by jdelobel** [openrewrite/rewrite-maven-plugin#424] opened 2022-09-30 09:58 UTC
Hi,

I have this error when i exec the remove command since  version 4.34.0. 

[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.34.0:remove (default-cli) on project acw_agreg-comptes-wsserver: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.34.0:remove failed: No version provided for dependency javax:javaee-api -> [Help 1]

**Comment by tkvangorder** [comment] 2022-09-30 18:16
@jdelobel 

Remove is attempting to parse your maven build file (so it can then remove the plugin). It looks like this failure is happening during the initial parse step. Can you provide the pom file that reproduces the issue? It would also be helpful to include a stack trace (by running with maven with the `-e` option.

**Comment by tkvangorder** [comment] 2022-10-24 21:58
@jdelobel I am going to close this issue because there is really not enough information. I might recommend retrying this on 4.36.0, as we have made some enhancements to the Maven resolution. If you are finding this is still a problem, I am happy to re-open the issue.

**Closed by tkvangorder** 2022-10-24 21:58 UTC
Labels: bug, question
