### ISSUE TITLE
rewrite:run gives StackOverflowError

### ISSUE THREAD

**Issue by tisonkun** [openrewrite/rewrite-maven-plugin#434] opened 2022-11-11 06:44 UTC
Another issue:

```
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.36.0:run (default-cli) on project pulsar-client-admin-shade-test: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.36.0:run failed: java.lang.StackOverflowError -> [Help 1]
```

The same settings as above. https://github.com/openrewrite/rewrite-maven-plugin/issues/433#issue-1444979491

_Originally posted by @tisonkun in https://github.com/openrewrite/rewrite-maven-plugin/issues/433#issuecomment-1311292279_

**Comment by pway99** [comment] 2022-11-15 01:12
Thanks @tisonkun,

looks like this is associated with java 17 switch expressions
```log
[INFO] Apache Pulsar :: Tests :: Pulsar-Client-Admin-Shade Test FAILURE [03:16 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:42 min
[INFO] Finished at: 2022-11-14T17:07:20-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.37.0-SNAPSHOT:run (default-cli) on project pulsar-client-admin-shade-test: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.37.0-SNAPSHOT:run failed: java.lang.StackOverflowError -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.openrewrite.maven:rewrite-maven-plugin:4.37.0-SNAPSHOT:run (default-cli) on project pulsar-client-admin-shade-test: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.37.0-SNAPSHOT:run failed: java.lang.StackOverflowError
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.openrewrite.maven:rewrite-maven-plugin:4.37.0-SNAPSHOT:run failed: java.lang.StackOverflowError
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.openrewrite.internal.RecipeRunException: java.lang.StackOverflowError
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:326)
    at org.openrewrite.TreeVisitor.reduce (TreeVisitor.java:238)
    at org.openrewrite.java.tree.J$SwitchExpression.getType (J.java:4653)
    at org.openrewrite.java.JavaVisitor.visitSwitchExpression (JavaVisitor.java:1042)
    at org.openrewrite.java.tree.J$SwitchExpression.acceptJava (J.java:4665)
    at org.openrewrite.java.tree.J.accept (J.java:64)
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:278)
    at org.openrewrite.TreeVisitor.reduce (TreeVisitor.java:238)
    at org.openrewrite.java.tree.J$SwitchExpression.getType (J.java:4653)
    at org.openrewrite.java.JavaVisitor.visitSwitchExpression (JavaVisitor.java:1042)
    at org.openrewrite.java.tree.J$SwitchExpression.acceptJava (J.java:4665)
    at org.openrewrite.java.tree.J.accept (J.java:64)
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:278)
    at org.openrewrite.TreeVisitor.reduce (TreeVisitor.java:238)
    at org.openrewrite.java.tree.J$SwitchExpression.getType (J.java:4653)
    at org.openrewrite.java.JavaVisitor.visitSwitchExpression (JavaVisitor.java:1042)
    at org.openrewrite.java.tree.J$SwitchExpression.acceptJava (J.java:4665)
    at org.openrewrite.java.tree.J.accept (J.java:64)
    at org.openrewrite.TreeVisitor.visit (TreeVisitor.java:278)
    at org.openrewrite.TreeVisitor.reduce (TreeVisitor.java:238)
    at org.openrewrite.java.tree.J$SwitchExpression.getType (J.java:4653)
    at org.openrewrite.java.JavaVisitor.visitSwitchExpression (JavaVisitor.java:1042)
    at org.openrewrite.java.tree.J$SwitchExpression.acceptJava (J.java:4665)
   ...
```

**Comment by traceyyoshima** [comment] 2022-11-16 16:22
@tisonkun, thanks for reporting the issue!

I will close the issue as a duplicate of [#2357](https://github.com/openrewrite/rewrite/issues/2357).

**Closed by traceyyoshima** 2022-11-16 16:22 UTC
Labels: bug, duplicate
