### ISSUE TITLE
Problem with resolving rewrite plugin on parent pom

### ISSUE THREAD

**Issue by christianhahnsft22** [openrewrite/rewrite-maven-plugin#475] opened 2023-01-18 12:05 UTC
Hi !

When I try to use openrewrite inside a parent pom the rewrite maven plugin is not found. Here a sample parent pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.old</groupId>
    <artifactId>old-artifactId</artifactId>
    <version>1.2.3</version>
    <packaging>pom</packaging>
    <name>my-name</name>
    <modules>
        <module>a</module>
        <module>b</module>
        <module>c</module>
        <module>project-ear</module>
    </modules>

    

    <dependencyManagement>
        <dependencies>
		....
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openrewrite.maven</groupId>
                <artifactId>rewrite-maven-plugin</artifactId>
                <version>4.38.2</version>
                <configuration>
                    <activeRecipes>
                        <recipe>com.test.ChangePackage</recipe>
                    </activeRecipes>
                </configuration>
                <executions>
                    <execution>
                        <id>rewrite-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>runNoFork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <extensions>
            <extension>
                <groupId>org.apache.maven.wagon</groupId>
                <artifactId>wagon-ssh</artifactId>
                <version>3.4.3</version>
            </extension>
        </extensions>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.10.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.2.2</version>
                </plugin>
                ....
            </plugins>
        </pluginManagement>
    </build>
</project>
```

If I then try to call my recipe I cannot run `mvn rewrite:run` but need to call the plugin like this:

`mvn org.openrewrite.maven:rewrite-maven-plugin:run`

**Comment by timtebeek** [comment] 2023-01-18 12:12
Confirmed with Maven 3.8.7 
```
$ mvn -version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /home/tim/.sdkman/candidates/maven/current
Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /home/tim/.sdkman/candidates/java/17.0.5-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-58-generic", arch: "amd64", family: "unix"
$ mvn rewrite:run
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 61 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (21 kB at 88 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.420 s
[INFO] Finished at: 2023-01-18T13:11:35+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'rewrite' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/tim/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

**Comment by timtebeek** [comment] 2023-01-18 12:40
Reading the [plugin prefix resolution documentation](https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html) it's not clear to me why this would not resolve for this sample project. On one of my own multi module Maven projects the shorthand still works fine. Worst case you can configure a `pluginGroup` in your `settings.xml`, but that should not be necessary.

**Comment by timtebeek** [comment] 2023-01-18 19:09
So it appears we've encountered this before #103 ; the accidental way I found around this is using a profile on the parent.

```xml
<profile>
  <id>openrewrite</id>
  <build>
    <plugins>
      <plugin>
        <groupId>org.openrewrite.maven</groupId>
        <artifactId>rewrite-maven-plugin</artifactId>
        <version>4.38.2</version>
        <configuration>
          <activeRecipes>
            <recipe>org.openrewrite.java.cleanup.Cleanup</recipe>
          </activeRecipes>
          <failOnDryRunResults>true</failOnDryRunResults>
        </configuration>
      </plugin>
    </plugins>
  </build>
</profile>
```
Welcome to see if that will get you past this point for now and applying recipes!

**Comment by anand188** [comment] 2024-08-29 06:00
Hi , any ETA or fix version when this will be fixed ?

**Comment by yurym-ping** [comment] 2024-10-28 22:54
+1

**Comment by timtebeek** [comment] 2024-10-28 23:19
Hi! Trust me that I'd very much like to see this fixed, especially as there appears to be quite some interest. I just don't quite know why this does not work in the first place already. I've [added a commit just now](https://github.com/openrewrite/rewrite-maven-plugin/commit/bd2750980ac34e65cd04cefc55f98424b4201a73) in an attempt to make this prefix explicit, but it's not clear to me if that'll help much. Any help appreciated!

**Comment by timtebeek** [comment] 2024-10-29 11:57
I've just done a .patch release of the rewrite maven with the above fix, which shows improvement on a quick test project:
- https://github.com/openrewrite/rewrite-maven-plugin/releases/tag/v5.43.2

Tentatively closing this issue already; do let me know your findings with that new version as well. Thanks all!

**Closed by timtebeek** 2024-10-29 11:57 UTC
Labels: bug

**Comment by TobiX** [comment] 2024-11-05 10:06
Huh? Hasn't `<goalPrefix>` been mandatory since Maven-Plugin-Tools 3.11.0 (released in January, see https://issues.apache.org/jira/browse/MPLUGIN-450)? Funky that it still worked and broke... randomly?

**Comment by asturio** [comment] 2025-02-05 10:21
I know, this issue is already closed, but I have maybe some new infos. I have the same problem now, after using openrewrite in 3 other projects (2 of them are multi-modules projects). With these projects I didn't use a profile, and it worked fine.

And in the "problem-project" creating a profile for openrewrite and using it doesn't help. But in this multi-module-project there is one subtle difference. One of the modules is a bom/pom module.

The bom-module is the first module of the root-pom. In that position, the "rewrite" can't be resolved at all.

If I put the bom-module in the last position, the "rewrite" is found and run on all previous modules, and in the bom-module, it fails.

My workaround would be than to create a profile für openrewrite, that disables the bom-module.
